# FluorCam Data Analysis Toolbox - Main Application Entry Point
# DESCRIPTION: Comprehensive Shiny application for analyzing chlorophyll fluorescence data
# AUTHORS: Cécile LECAMPION, Ben FIELD
# VERSION: 1.0
# CREATED: 2025
# LAST MODIFIED: 2025
#
# PURPOSE: 
# This Shiny application provides a user-friendly interface for analyzing fluorescence data
# measured with FluorCam systems. It processes .TXT files generated by FluorCam software
# and performs statistical analysis without requiring R programming knowledge.
#
# KEY FEATURES:
# - Automated data processing from FluorCam .TXT files
# - Statistical analysis (parametric and non-parametric)
# - Bar plot analysis with ANOVA/Kruskal-Wallis testing
# - Curve analysis using quantile Generalized Additive Models (qGAM)
# - Publication-quality visualization with statistical annotations
# - Comprehensive export functionality for plots and statistical results
# - User-friendly interface with step-by-step workflow guidance
#
# TARGET USERS:
# - Plant scientists and researchers using FluorCam systems
# - Students and technicians with limited R programming experience
# - Anyone needing to analyze chlorophyll fluorescence data efficiently
#
# SUPPORTED DATA FORMATS:
# - FluorCam .TXT files with systematic naming (VAR1_VAR2_VAR3.TXT)
# - Time-course data with multiple measurement parameters
# - Experimental designs with grouping and faceting variables
#
# ANALYSIS CAPABILITIES:
# - Bar Plot Analysis: Group comparisons with statistical testing
#   * Automatic normality testing (Shapiro-Wilk)
#   * ANOVA or Kruskal-Wallis tests
#   * Tukey HSD or Dunn post-hoc tests
#   * Compact letter display for significance grouping
# - Curve Analysis: Time-course data with trend analysis
#   * qGAM (quantile Generalized Additive Models) fitting
#   * Control group comparisons
#   * Confidence intervals and statistical testing
#   * Flexible time unit specification
#
# EXPORT FORMATS:
# - Statistical Results: .zip archive with .txt files (universal compatibility)
# - Plots: PNG, PDF, SVG, JPEG with customizable dimensions and units
#
# SYSTEM REQUIREMENTS:
# - R 4.0+ recommended
# - All required packages automatically installed from CRAN
# - Cross-platform compatibility (Windows, macOS, Linux)
# - Modern web browser for optimal user interface experience

# LICENSE INFORMATION
# Copyright (c) 2025 Cécile LECAMPION, Ben FIELD
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# APPLICATION ARCHITECTURE
# STRATEGY: Modular design with separation of concerns
# - global.R: Package management and global configuration
# - helpers.R: Data processing and statistical analysis functions
# - ui.R: User interface definition with dashboard layout
# - server.R: Server-side logic and reactive programming
# - App.R: Application entry point and orchestration
#
# DESIGN PRINCIPLES:
# - Single Responsibility: Each file has a clear, focused purpose
# - Modularity: Functions are reusable and independently testable
# - User Experience: Intuitive workflow with progressive disclosure
# - Robustness: Comprehensive error handling and input validation
# - Extensibility: Easy to add new features and analysis methods
#
# REACTIVE ARCHITECTURE:
# - Event-driven analysis execution
# - Efficient data storage and retrieval
# - Dynamic UI generation based on data structure
# - Automatic plot and statistics updates

# DEPLOYMENT AND USAGE INSTRUCTIONS
# RUNNING LOCALLY:
# 1. Ensure R 4.0+ is installed
# 2. Open R/RStudio and set working directory to this folder
# 3. Run: source("App.R") or click "Run App" in RStudio
# 4. Application will open in default web browser
#
# FIRST-TIME SETUP:
# - Required packages will be automatically installed on first run
# - Installation may take several minutes depending on system
# - Internet connection required for package installation
#
# DATA PREPARATION:
# 1. Ensure FluorCam files follow naming convention: VAR1_VAR2_VAR3.TXT
# 2. Place all data files in a single directory
# 3. Verify files contain consistent column structure
#
# WORKFLOW:
# 1. Configure file naming pattern
# 2. Load data from directory
# 3. Set analysis parameters
# 4. Execute analysis
# 5. Export results and plots
#
# TROUBLESHOOTING:
# - Check file naming follows VAR1_VAR2_VAR3.TXT pattern
# - Ensure all files have identical column structure
# - Verify sufficient sample sizes for statistical analysis
# - Check browser compatibility for optimal UI experience

# CITATION AND ACKNOWLEDGMENTS
# RECOMMENDED CITATION:
# Lecampion, C., & Field, B. (2025). FluorCam Data Analysis Toolbox. 
# R Shiny Application for Chlorophyll Fluorescence Analysis.
#
# ACKNOWLEDGMENTS:
# - Built using R Shiny framework
# - Statistical methods implemented using rstatix and qgam packages
# - Visualization powered by ggplot2
# - UI components from shinydashboard and related packages
#
# CONTRIBUTING:
# Bug reports, feature requests, and contributions are welcome.
# Please follow standard R package development practices.

# SOURCE CODE LOADING
# STRATEGY: Sequential loading of application components
# PURPOSE: Ensure proper dependency resolution and initialization order

# STEP 1: Global Configuration and Package Management
# STRATEGY: Load all dependencies and global settings first
# PURPOSE: Establish foundation for all subsequent components
source("global.R")    # Package management, global options, utility functions

# STEP 2: Helper Functions and Analysis Logic
# STRATEGY: Load data processing and statistical functions
# PURPOSE: Make all analysis capabilities available to server
source("helpers.R")   # Statistical functions, data processing, visualization

# STEP 3: User Interface Definition
# STRATEGY: Load UI definition after dependencies are available
# PURPOSE: Ensure all UI components can access required packages
source("ui.R")        # Dashboard layout, input controls, output displays

# STEP 4: Server Logic Implementation
# STRATEGY: Load server logic last to access all previous components
# PURPOSE: Complete reactive system with access to UI and helper functions
source("server.R")    # Reactive logic, event handling, analysis execution

# APPLICATION LAUNCH
# STRATEGY: Simple application instantiation after all components loaded
# PURPOSE: Start the Shiny application with UI and server components
# CONFIGURATION: Uses default settings optimized for local development

# Launch the Shiny application
# PARAMETERS:
# - ui: User interface object from ui.R
# - server: Server function from server.R
# - options: Default Shiny options (auto-detect available port, open browser)
shinyApp(ui = ui, server = server)

# ALTERNATIVE LAUNCH OPTIONS (commented out):
# 
# For specific port:
# shinyApp(ui = ui, server = server, options = list(port = 3838))
#
# For deployment (disable browser auto-launch):
# shinyApp(ui = ui, server = server, options = list(launch.browser = FALSE))
#
# For development with auto-reload:
# runApp(launch.browser = TRUE, display.mode = "showcase")

# END OF APPLICATION ENTRY POINT